### PR TITLE
Add other branches of raspberrypi kernel as seperate packages.

### PR DESCRIPTION
**Pull request by Titaniumtown**
I renamed some folders, and added files from previous commits.
I feel like this would be a better solution than what is currently being done. For instance, the linux-raspberrypi4 package had flip flopped from 4.19 to 5.4, I think that's unnecessary, and each branch should just be independent packages.

Another thing, do you think it would be a better idea to, instead of specifying specific commits to download the kernel from, just make it a vcs package that gets the latest commit from that branch? I could add that to this PR if you want.

Thoughts?

### CODE REVIEW

**Comment by Titaniumtown** [comment]
relates to my issue: #4

**Comment by Titaniumtown** [comment]
Just realized I got to rename the packages, lol. Give me a sec.

**Comment by Titaniumtown** [comment]
@moonman one issue w/ my PR atm, it prompts me for some config info. Is this stuff that has to added to 'config' file?

**Comment by Titaniumtown** [comment]
I'm doing more testing.

**Comment by Titaniumtown** [comment]
output package names are kinda ugly though: 
`linux-raspberrypi4-4.19.y-4.19.122.r798163.gf0e620550b8b-1-aarch64.pkg.tar.xz`

**Comment by moonman** [comment]
Please see my answer in issues.

**Pull request closed without merging**
